import type { Metadata } from "next";
// import localFont from "next/font/local";
import "./globals.css";
import Appbar from "@/components/Appbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Appbar />
        <main className="mx-auto my-8 max-w-4xl px-4 ">{children}</main>
      </body>
    </html>
  );
}
